# Generated by Django 3.2.3 on 2021-05-19 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('funcionarios', '0002_auto_20210519_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='empresas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa'),
        ),
    ]
