# Generated by Django 3.2.3 on 2021-05-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_documento_arquivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='funcionarios',
            new_name='pertence',
        ),
    ]
